// File: MyTrip5/View/ThanksToView.swift
// Copyright H2so4 Consulting LLC, 2026

import SwiftUI

struct ThanksToView: View {
    @Environment(\.dismiss) private var dismiss // End dismiss
    @State private var entries: [AttributionStore.Entry] = [] // End entries

    var body: some View {
        NavigationStack {
            List {
                Section("Photo Provider") {
                    Text("Iconic travel photos may come from Pexels or be generated by OpenAI.")
                    Link("Pexels License", destination: URL(string: "https://www.pexels.com/license/")!) // End Link
                } // End Section Photo Provider

                Section("Pexels Credits") {
                    let pexels = entries.filter { $0.provider == .pexels } // End pexels
                    if pexels.isEmpty {
                        Text("No Pexels attributions yet.")
                            .foregroundStyle(.secondary)
                    } else {
                        ForEach(pexels) { entry in
                            VStack(alignment: .leading, spacing: 6) {
                                Text("Photo by \(entry.photographer ?? "Unknown")")
                                    .font(.headline)

                                if let pageString = entry.pageURL, let page = URL(string: pageString) {
                                    Link("View on Pexels", destination: page)
                                } // End if page link

                                if let image = URL(string: entry.imageURL) {
                                    Link("Image URL", destination: image)
                                        .font(.footnote)
                                        .foregroundStyle(.secondary)
                                } // End if image link
                            } // End VStack Pexels entry
                            .padding(.vertical, 4)
                        } // End ForEach pexels
                    } // End if/else pexels.isEmpty
                } // End Section Pexels Credits

                Section("OpenAI Generated") {
                    let openai = entries.filter { $0.provider == .openai } // End openai
                    if openai.isEmpty {
                        Text("No OpenAI generated images yet.")
                            .foregroundStyle(.secondary)
                    } else {
                        ForEach(openai) { entry in
                            VStack(alignment: .leading, spacing: 6) {
                                Text("Generated iconic image")
                                    .font(.headline)

                                if let image = URL(string: entry.imageURL) {
                                    Link("Image URL", destination: image)
                                        .font(.footnote)
                                        .foregroundStyle(.secondary)
                                } // End if image link

                                #if DEBUG
                                if let prompt = entry.prompt, !prompt.isEmpty {
                                    Text("Prompt: \(prompt)")
                                        .font(.footnote)
                                        .foregroundStyle(.secondary)
                                        .textSelection(.enabled)
                                } // End if prompt (DEBUG)
                                #endif
                            } // End VStack OpenAI entry
                            .padding(.vertical, 4)
                        } // End ForEach openai
                    } // End if/else openai.isEmpty
                } // End Section OpenAI Generated

                Section {
                    Button(role: .destructive) {
                        AttributionStore.clear()
                        entries = []
                    } label: {
                        Text("Clear Attributions")
                    } // End Button Clear
                } // End Section Clear
            } // End List (long)
            .navigationTitle("Thanks To")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() } // End Button Done
                } // End ToolbarItem Done
            } // End toolbar
            .onAppear {
                entries = AttributionStore.all()
            } // End onAppear
        } // End NavigationStack
    } // End body
} // End ThanksToView
